[WIP] TS Polymer 3 Class: ServerList
Jigsaw-Code/outline-client pull request #1102
Opened 2021-11-15 20:20 UTC by daniellacosse

2021-11-15 21:46 UTC, daniellacosse commented
HAHA I'm shocked that this passed

2021-11-17 18:45 UTC, daniellacosse commented on src/www/ui_components/server_card.ts
> +@customElement('server-card') export class ServerCard extends LegacyElementMixin
are we cool with `LegacyElementMixin` or should I try to remove it?

2021-11-19 17:17 UTC, daniellacosse commented
@fortuna I'm still dealing with the broken ESModule support, but if you get a head start on this I can address your comments while you're out.

2021-11-19 20:14 UTC, fortuna requested changes

2021-11-19 20:14 UTC, fortuna commented on src/www/ui_components/server_list.ts
> +export class ServerList extends PolymerElement {
Let's convert only this element in this PR. The TS code can depend on the JS code (use the .js extension in the import), and even leverage the type guessing from TS. We can also add JSDoc type annotations like we do in the manager.

Example of TS depending on JS: https://github.com/Jigsaw-Code/outline-server/blob/f340c0d484514d306ce5f68a4bb5c7ec82d5a3b5/src/server_manager/web_app/ui_components/outline-gcp-oauth-step.ts

Example js with type annotations depending on both js and ts: https://github.com/Jigsaw-Code/outline-server/blob/f340c0d484514d306ce5f68a4bb5c7ec82d5a3b5/src/server_manager/web_app/ui_components/app-root.js

That was all before Ben converted the elements all to TS: https://github.com/Jigsaw-Code/outline-server/pull/997

2021-11-22 17:13 UTC, closed without merging