chore: upgrade sentry
Jigsaw-Code/outline-client pull request #1558
Opened 2023-01-19 19:49 UTC by daniellacosse

simply starting with this just to see if it does the trick

2023-01-19 23:42 UTC, fortuna approved these changes

2023-01-19 23:42 UTC, fortuna commented on package.json
> -    "@sentry/electron": "^3.0.7",
I doubt an upgrade will fix the problem. In fact, perhaps an upgrade broke it. (dependabot?)
Did you check https://github.com/getsentry/sentry-electron/blob/master/MIGRATION.md ?

/cc @jyyi1

2023-01-19 23:42 UTC, fortuna commented on package.json
> -    "@sentry/electron": "^3.0.7",
I'm not saying we shouldn't upgrade, but it would be helpful to understand what the problem actually is and if we are using the APIs correctly.

2023-01-20 00:49 UTC, jyyi1 requested changes
Unfortunately the client is not loading in Windows. It might involve a lot of work to upgrade Sentry SDK. I can provide some help for Windows/Linux upgrade later if you need.

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/93548144/213594341-bfb6562c-9c51-48a5-b372-5a985cff7cb7.png">

2023-01-20 19:52 UTC, jyyi1 approved these changes
The app is loading, though Sentry messages are still not able to reach the backend. But at least I think it's safe to upgrade Sentry SDK now. Thanks.

2023-01-20 20:05 UTC, jyyi1 approved these changes

2023-01-20 20:19 UTC, fortuna approved these changes

2023-01-20 20:28 UTC, merged