chore(client): move the client to its own subfolder
Jigsaw-Code/outline-client pull request #1838
Opened 2024-02-12 19:07 UTC by daniellacosse

I was able to successfully move the client into its own subfolder:

![Screenshot 2024-02-12 at 1 49 21 PM](https://github.com/Jigsaw-Code/outline-client/assets/3759828/6c617821-8cac-484f-b506-cd4933428275)

TODO:

- [x] should i move build into the root? or try to mess with `ROOT_DIR`?
- [x] basic documentation
- [x] move third_party into the root (need help from @jyyi1)
- [ ] unbreak it... again
  - [x] electron
  - [ ] windows (it can't find the env.nsh)
  - [x] android working in the CI (dialer.Dial undefined??)
  - [x] maccatalyst working in the CI

2024-02-21 22:23 UTC, fortuna requested changes
A number of tests are still failing, so I think there's still stuff to figure out.

2024-02-21 22:23 UTC, fortuna commented on client/third_party/jsign/.gitignore
third_party must stay in the root:
- http://go/thirdparty/non-google3#WhereInThirdParty
- http://go/thirdparty/where#separate-out-dependencies

2024-02-21 22:23 UTC, fortuna commented on README.md
> +TODO
This is a must have. At a minimum we should link to the client and the manager

2024-02-21 22:23 UTC, fortuna commented on README.md
> -![Build and Test](https://github.com/Jigsaw-Code/outline-client/actions/workflows/build_and_test_debug.yml/badge.svg?branch=master) [![Mattermost](https://badgen.net/badge/Mattermost/Outline%20Commun
This should probably stay here?

2024-02-21 22:23 UTC, fortuna commented on client/README.md
> +![Build and Test](https://github.com/Jigsaw-Code/outline-apps/actions/workflows/build_and_test_debug.yml/badge.svg?branch=master) [![Mattermost](https://badgen.net/badge/Mattermost/Outline%20Communit
@https://github.com/Jigsaw-Code/outline-apps/actions/workflows/build_and_test_debug.yml/badge.svg?branch=master is not found. It was broken in the previous PR

2024-02-21 22:23 UTC, fortuna commented on tools/OutlineService/OutlineService/bin/Release/OutlineService.exe.config
Why is this being deleted?

2024-02-23 00:02 UTC, jyyi1 commented on client/third_party/jsign/.gitignore
I think Vini means we don't touch or move anything in `third_party`, and make sure it's in the root path. There should be only one `third_party` folder in the repository root.

2024-02-29 03:37 UTC, jyyi1 reviewed
For the Windows build failure, we just need to specify the `projectDir` when [calling electron-builder](https://github.com/Jigsaw-Code/outline-apps/blob/f3e10d6a5a9012bf1ceba165a04d53e39cc17915/src/electron/build.action.mjs#L64-L82) (currently it's `D:\a\outline-apps\outline-apps`, but it should be `D:\a\outline-apps\outline-apps\client` because [`env.nsh` will be generated there](https://github.com/Jigsaw-Code/outline-apps/blob/f3e10d6a5a9012bf1ceba165a04d53e39cc17915/src/electron/build_main.action.mjs#L60)), similar to [what we did in manager](https://github.com/Jigsaw-Code/outline-apps/blob/f3e10d6a5a9012bf1ceba165a04d53e39cc17915/server_manager/electron_app/package.action.sh#L26).

2024-03-07 21:32 UTC, jyyi1 commented
> @jyyi1 I've updated the SDK - didn't you say some naming changed? What should I fix

Basically anytime you see an error: `dialer.Dial undefined (type transport.StreamDialer has no field or method Dial)`, just rename the `Dial` in the source code to `DialStream` (if the error message mentions `StreamDialer`) or `DialPacket` (if the error message mentions `PacketDialer`).

2024-03-14 19:18 UTC, fortuna requested changes

2024-03-14 19:18 UTC, fortuna commented on server_manager/electron_app/build.action.sh
> +node client/src/build/run_action.mjs server_manager/web_app/build
Why is the Manager referring to the client?

2024-03-14 19:29 UTC, fortuna commented
@daniellacosse can we perhaps only migrate Cordova in this PR so we can move forward quickly?

2024-04-01 18:26 UTC, closed without merging