chore(client): move `outline/device` and rename tun2socks to backend
Jigsaw-Code/outline-client pull request #1962
Opened 2024-04-08 19:32 UTC by daniellacosse

Note that this blocks the removal of `client/src`

2024-04-08 22:36 UTC, jyyi1 reviewed
Thanks, this is cleaner. The makefile seems to conflict with #1960 , you might want to sync with @fortuna on who's gonna merge first.

2024-04-08 22:36 UTC, jyyi1 commented on .github/workflows/build_and_test_debug_client.yml
>        - name: Build Tun2Socks (required for Test OutlineAppleLib)
*minor* Do you think we need to update the name from `Build Tun2Socks` to `Build Backend` in this file?

2024-04-08 22:36 UTC, jyyi1 commented on Makefile
> +ELECTRON_PKG="./client/src/backend/outline/electron"
Please double confirm this won't change the final binary name (it should be `tun2socks` for Linux and `tun2socks.exe` for Windows).

Or maybe we should actually update it to `backend` and `backend.exe`? It's up to you.

2024-04-10 18:17 UTC, fortuna requested changes
Let's prioritize fixing the client first. I worry this refactoring will further break things. 
Once the client is fixed and verified, we can proceed with this change.

2024-04-15 16:07 UTC, closed without merging