Add "watch" actions which run `tsc` in watch mode
Jigsaw-Code/outline-client pull request #651
Opened 2019-08-21 18:55 UTC by JonathanDCohen

"watch" mode watches for any changed files or directories, recompiling anything which has been changed without needing a full rebuild.  This can be used during development to speed up rebuild times and edit-compile iteration.

2019-10-18 20:31 UTC, fortuna commented on src/electron/watch_action.sh
> +yarn do src/www/build
Maybe this should be `yarn do src/www/watch&` ?

2019-10-18 20:31 UTC, fortuna submitted a review, later dismissed

2021-11-08 20:52 UTC, daniellacosse commented
@fortuna can we merge this? it'd be very useful for me

also, i think this outmodes https://github.com/Jigsaw-Code/outline-client/pull/759 and https://github.com/Jigsaw-Code/outline-client/pull/534

2021-11-08 23:15 UTC, fortuna approved these changes

2021-11-08 23:16 UTC, fortuna requested changes
Wait

2021-11-08 23:17 UTC, fortuna commented
@daniellacosse Setting up the dev server will be a lot more productive. Also, we use webpack now. The change to webpack happened after this PR. We shouldn't be calling tsc directly.

2021-11-08 23:17 UTC, closed without merging

2021-11-08 23:18 UTC, fortuna commented
See Outline Manager for how we set up the dev server.

2021-11-09 15:30 UTC, daniellacosse commented
> @daniellacosse Setting up the dev server will be a lot more productive. Also, we use webpack now. The change to webpack happened after this PR. We shouldn't be calling tsc directly.

We should close those other issues then, yeah?  https://github.com/Jigsaw-Code/outline-client/pull/759 and https://github.com/Jigsaw-Code/outline-client/pull/534?

2021-11-09 16:40 UTC, fortuna commented
No, closing people bugs and PRs is usually bad. We can do that once we add the dev server.

2021-11-09 16:41 UTC, daniellacosse commented
> No, closing people bugs and PRs is usually bad. We can do that once we add the dev server.

Ah, right, though my understanding is correct